// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MediaGraphConfig.proto
package com.youmehe.mediatry;

public final class MediaGraphConfigProto {
  private MediaGraphConfigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MediaGraphConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MediaGraphConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The nodes.
     * </pre>
     *
     * <code>repeated .MediaGraphConfig.Node node = 1;</code>
     */
    java.util.List<MediaGraphConfigProto.MediaGraphConfig.Node> 
        getNodeList();
    /**
     * <pre>
     * The nodes.
     * </pre>
     *
     * <code>repeated .MediaGraphConfig.Node node = 1;</code>
     */
    MediaGraphConfigProto.MediaGraphConfig.Node getNode(int index);
    /**
     * <pre>
     * The nodes.
     * </pre>
     *
     * <code>repeated .MediaGraphConfig.Node node = 1;</code>
     */
    int getNodeCount();
    /**
     * <pre>
     * The nodes.
     * </pre>
     *
     * <code>repeated .MediaGraphConfig.Node node = 1;</code>
     */
    java.util.List<? extends MediaGraphConfigProto.MediaGraphConfig.NodeOrBuilder> 
        getNodeOrBuilderList();
    /**
     * <pre>
     * The nodes.
     * </pre>
     *
     * <code>repeated .MediaGraphConfig.Node node = 1;</code>
     */
    MediaGraphConfigProto.MediaGraphConfig.NodeOrBuilder getNodeOrBuilder(
        int index);

    /**
     * <code>repeated string input_stream = 2;</code>
     */
    java.util.List<java.lang.String>
        getInputStreamList();
    /**
     * <code>repeated string input_stream = 2;</code>
     */
    int getInputStreamCount();
    /**
     * <code>repeated string input_stream = 2;</code>
     */
    java.lang.String getInputStream(int index);
    /**
     * <code>repeated string input_stream = 2;</code>
     */
    com.google.protobuf.ByteString
        getInputStreamBytes(int index);

    /**
     * <code>repeated string output_stream = 3;</code>
     */
    java.util.List<java.lang.String>
        getOutputStreamList();
    /**
     * <code>repeated string output_stream = 3;</code>
     */
    int getOutputStreamCount();
    /**
     * <code>repeated string output_stream = 3;</code>
     */
    java.lang.String getOutputStream(int index);
    /**
     * <code>repeated string output_stream = 3;</code>
     */
    com.google.protobuf.ByteString
        getOutputStreamBytes(int index);
  }
  /**
   * Protobuf type {@code MediaGraphConfig}
   */
  public  static final class MediaGraphConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MediaGraphConfig)
      MediaGraphConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MediaGraphConfig.newBuilder() to construct.
    private MediaGraphConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MediaGraphConfig() {
      node_ = java.util.Collections.emptyList();
      inputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      outputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MediaGraphConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                node_ = new java.util.ArrayList<MediaGraphConfigProto.MediaGraphConfig.Node>();
                mutable_bitField0_ |= 0x00000001;
              }
              node_.add(
                  input.readMessage(MediaGraphConfigProto.MediaGraphConfig.Node.parser(), extensionRegistry));
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                inputStream_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              inputStream_.add(s);
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                outputStream_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              outputStream_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          node_ = java.util.Collections.unmodifiableList(node_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          inputStream_ = inputStream_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          outputStream_ = outputStream_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MediaGraphConfigProto.internal_static_MediaGraphConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MediaGraphConfigProto.internal_static_MediaGraphConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MediaGraphConfigProto.MediaGraphConfig.class, MediaGraphConfigProto.MediaGraphConfig.Builder.class);
    }

    public interface NodeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:MediaGraphConfig.Node)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>string calculator = 2;</code>
       */
      java.lang.String getCalculator();
      /**
       * <code>string calculator = 2;</code>
       */
      com.google.protobuf.ByteString
          getCalculatorBytes();

      /**
       * <code>repeated string input_stream = 3;</code>
       */
      java.util.List<java.lang.String>
          getInputStreamList();
      /**
       * <code>repeated string input_stream = 3;</code>
       */
      int getInputStreamCount();
      /**
       * <code>repeated string input_stream = 3;</code>
       */
      java.lang.String getInputStream(int index);
      /**
       * <code>repeated string input_stream = 3;</code>
       */
      com.google.protobuf.ByteString
          getInputStreamBytes(int index);

      /**
       * <code>repeated string output_stream = 4;</code>
       */
      java.util.List<java.lang.String>
          getOutputStreamList();
      /**
       * <code>repeated string output_stream = 4;</code>
       */
      int getOutputStreamCount();
      /**
       * <code>repeated string output_stream = 4;</code>
       */
      java.lang.String getOutputStream(int index);
      /**
       * <code>repeated string output_stream = 4;</code>
       */
      com.google.protobuf.ByteString
          getOutputStreamBytes(int index);
    }
    /**
     * <pre>
     * A single node in the DAG.
     * </pre>
     *
     * Protobuf type {@code MediaGraphConfig.Node}
     */
    public  static final class Node extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:MediaGraphConfig.Node)
        NodeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Node.newBuilder() to construct.
      private Node(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Node() {
        name_ = "";
        calculator_ = "";
        inputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        outputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Node(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                calculator_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  inputStream_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000004;
                }
                inputStream_.add(s);
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                  outputStream_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000008;
                }
                outputStream_.add(s);
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
            inputStream_ = inputStream_.getUnmodifiableView();
          }
          if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
            outputStream_ = outputStream_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MediaGraphConfigProto.internal_static_MediaGraphConfig_Node_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MediaGraphConfigProto.internal_static_MediaGraphConfig_Node_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MediaGraphConfigProto.MediaGraphConfig.Node.class, MediaGraphConfigProto.MediaGraphConfig.Node.Builder.class);
      }

      private int bitField0_;
      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CALCULATOR_FIELD_NUMBER = 2;
      private volatile java.lang.Object calculator_;
      /**
       * <code>string calculator = 2;</code>
       */
      public java.lang.String getCalculator() {
        java.lang.Object ref = calculator_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          calculator_ = s;
          return s;
        }
      }
      /**
       * <code>string calculator = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCalculatorBytes() {
        java.lang.Object ref = calculator_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          calculator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int INPUT_STREAM_FIELD_NUMBER = 3;
      private com.google.protobuf.LazyStringList inputStream_;
      /**
       * <code>repeated string input_stream = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInputStreamList() {
        return inputStream_;
      }
      /**
       * <code>repeated string input_stream = 3;</code>
       */
      public int getInputStreamCount() {
        return inputStream_.size();
      }
      /**
       * <code>repeated string input_stream = 3;</code>
       */
      public java.lang.String getInputStream(int index) {
        return inputStream_.get(index);
      }
      /**
       * <code>repeated string input_stream = 3;</code>
       */
      public com.google.protobuf.ByteString
          getInputStreamBytes(int index) {
        return inputStream_.getByteString(index);
      }

      public static final int OUTPUT_STREAM_FIELD_NUMBER = 4;
      private com.google.protobuf.LazyStringList outputStream_;
      /**
       * <code>repeated string output_stream = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getOutputStreamList() {
        return outputStream_;
      }
      /**
       * <code>repeated string output_stream = 4;</code>
       */
      public int getOutputStreamCount() {
        return outputStream_.size();
      }
      /**
       * <code>repeated string output_stream = 4;</code>
       */
      public java.lang.String getOutputStream(int index) {
        return outputStream_.get(index);
      }
      /**
       * <code>repeated string output_stream = 4;</code>
       */
      public com.google.protobuf.ByteString
          getOutputStreamBytes(int index) {
        return outputStream_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (!getCalculatorBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, calculator_);
        }
        for (int i = 0; i < inputStream_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, inputStream_.getRaw(i));
        }
        for (int i = 0; i < outputStream_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, outputStream_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (!getCalculatorBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, calculator_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < inputStream_.size(); i++) {
            dataSize += computeStringSizeNoTag(inputStream_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getInputStreamList().size();
        }
        {
          int dataSize = 0;
          for (int i = 0; i < outputStream_.size(); i++) {
            dataSize += computeStringSizeNoTag(outputStream_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getOutputStreamList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof MediaGraphConfigProto.MediaGraphConfig.Node)) {
          return super.equals(obj);
        }
        MediaGraphConfigProto.MediaGraphConfig.Node other = (MediaGraphConfigProto.MediaGraphConfig.Node) obj;

        boolean result = true;
        result = result && getName()
            .equals(other.getName());
        result = result && getCalculator()
            .equals(other.getCalculator());
        result = result && getInputStreamList()
            .equals(other.getInputStreamList());
        result = result && getOutputStreamList()
            .equals(other.getOutputStreamList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + CALCULATOR_FIELD_NUMBER;
        hash = (53 * hash) + getCalculator().hashCode();
        if (getInputStreamCount() > 0) {
          hash = (37 * hash) + INPUT_STREAM_FIELD_NUMBER;
          hash = (53 * hash) + getInputStreamList().hashCode();
        }
        if (getOutputStreamCount() > 0) {
          hash = (37 * hash) + OUTPUT_STREAM_FIELD_NUMBER;
          hash = (53 * hash) + getOutputStreamList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static MediaGraphConfigProto.MediaGraphConfig.Node parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MediaGraphConfigProto.MediaGraphConfig.Node parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MediaGraphConfigProto.MediaGraphConfig.Node parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MediaGraphConfigProto.MediaGraphConfig.Node parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MediaGraphConfigProto.MediaGraphConfig.Node parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MediaGraphConfigProto.MediaGraphConfig.Node parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MediaGraphConfigProto.MediaGraphConfig.Node parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MediaGraphConfigProto.MediaGraphConfig.Node parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static MediaGraphConfigProto.MediaGraphConfig.Node parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static MediaGraphConfigProto.MediaGraphConfig.Node parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static MediaGraphConfigProto.MediaGraphConfig.Node parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MediaGraphConfigProto.MediaGraphConfig.Node parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(MediaGraphConfigProto.MediaGraphConfig.Node prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * A single node in the DAG.
       * </pre>
       *
       * Protobuf type {@code MediaGraphConfig.Node}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:MediaGraphConfig.Node)
          MediaGraphConfigProto.MediaGraphConfig.NodeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return MediaGraphConfigProto.internal_static_MediaGraphConfig_Node_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return MediaGraphConfigProto.internal_static_MediaGraphConfig_Node_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  MediaGraphConfigProto.MediaGraphConfig.Node.class, MediaGraphConfigProto.MediaGraphConfig.Node.Builder.class);
        }

        // Construct using MediaGraphConfigProto.MediaGraphConfig.Node.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          name_ = "";

          calculator_ = "";

          inputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          outputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return MediaGraphConfigProto.internal_static_MediaGraphConfig_Node_descriptor;
        }

        @java.lang.Override
        public MediaGraphConfigProto.MediaGraphConfig.Node getDefaultInstanceForType() {
          return MediaGraphConfigProto.MediaGraphConfig.Node.getDefaultInstance();
        }

        @java.lang.Override
        public MediaGraphConfigProto.MediaGraphConfig.Node build() {
          MediaGraphConfigProto.MediaGraphConfig.Node result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public MediaGraphConfigProto.MediaGraphConfig.Node buildPartial() {
          MediaGraphConfigProto.MediaGraphConfig.Node result = new MediaGraphConfigProto.MediaGraphConfig.Node(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          result.name_ = name_;
          result.calculator_ = calculator_;
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            inputStream_ = inputStream_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.inputStream_ = inputStream_;
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            outputStream_ = outputStream_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.outputStream_ = outputStream_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof MediaGraphConfigProto.MediaGraphConfig.Node) {
            return mergeFrom((MediaGraphConfigProto.MediaGraphConfig.Node)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(MediaGraphConfigProto.MediaGraphConfig.Node other) {
          if (other == MediaGraphConfigProto.MediaGraphConfig.Node.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (!other.getCalculator().isEmpty()) {
            calculator_ = other.calculator_;
            onChanged();
          }
          if (!other.inputStream_.isEmpty()) {
            if (inputStream_.isEmpty()) {
              inputStream_ = other.inputStream_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureInputStreamIsMutable();
              inputStream_.addAll(other.inputStream_);
            }
            onChanged();
          }
          if (!other.outputStream_.isEmpty()) {
            if (outputStream_.isEmpty()) {
              outputStream_ = other.outputStream_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureOutputStreamIsMutable();
              outputStream_.addAll(other.outputStream_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          MediaGraphConfigProto.MediaGraphConfig.Node parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (MediaGraphConfigProto.MediaGraphConfig.Node) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object calculator_ = "";
        /**
         * <code>string calculator = 2;</code>
         */
        public java.lang.String getCalculator() {
          java.lang.Object ref = calculator_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            calculator_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string calculator = 2;</code>
         */
        public com.google.protobuf.ByteString
            getCalculatorBytes() {
          java.lang.Object ref = calculator_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            calculator_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string calculator = 2;</code>
         */
        public Builder setCalculator(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          calculator_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string calculator = 2;</code>
         */
        public Builder clearCalculator() {
          
          calculator_ = getDefaultInstance().getCalculator();
          onChanged();
          return this;
        }
        /**
         * <code>string calculator = 2;</code>
         */
        public Builder setCalculatorBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          calculator_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList inputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureInputStreamIsMutable() {
          if (!((bitField0_ & 0x00000004) == 0x00000004)) {
            inputStream_ = new com.google.protobuf.LazyStringArrayList(inputStream_);
            bitField0_ |= 0x00000004;
           }
        }
        /**
         * <code>repeated string input_stream = 3;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getInputStreamList() {
          return inputStream_.getUnmodifiableView();
        }
        /**
         * <code>repeated string input_stream = 3;</code>
         */
        public int getInputStreamCount() {
          return inputStream_.size();
        }
        /**
         * <code>repeated string input_stream = 3;</code>
         */
        public java.lang.String getInputStream(int index) {
          return inputStream_.get(index);
        }
        /**
         * <code>repeated string input_stream = 3;</code>
         */
        public com.google.protobuf.ByteString
            getInputStreamBytes(int index) {
          return inputStream_.getByteString(index);
        }
        /**
         * <code>repeated string input_stream = 3;</code>
         */
        public Builder setInputStream(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureInputStreamIsMutable();
          inputStream_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string input_stream = 3;</code>
         */
        public Builder addInputStream(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureInputStreamIsMutable();
          inputStream_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string input_stream = 3;</code>
         */
        public Builder addAllInputStream(
            java.lang.Iterable<java.lang.String> values) {
          ensureInputStreamIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, inputStream_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string input_stream = 3;</code>
         */
        public Builder clearInputStream() {
          inputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string input_stream = 3;</code>
         */
        public Builder addInputStreamBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureInputStreamIsMutable();
          inputStream_.add(value);
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList outputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureOutputStreamIsMutable() {
          if (!((bitField0_ & 0x00000008) == 0x00000008)) {
            outputStream_ = new com.google.protobuf.LazyStringArrayList(outputStream_);
            bitField0_ |= 0x00000008;
           }
        }
        /**
         * <code>repeated string output_stream = 4;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getOutputStreamList() {
          return outputStream_.getUnmodifiableView();
        }
        /**
         * <code>repeated string output_stream = 4;</code>
         */
        public int getOutputStreamCount() {
          return outputStream_.size();
        }
        /**
         * <code>repeated string output_stream = 4;</code>
         */
        public java.lang.String getOutputStream(int index) {
          return outputStream_.get(index);
        }
        /**
         * <code>repeated string output_stream = 4;</code>
         */
        public com.google.protobuf.ByteString
            getOutputStreamBytes(int index) {
          return outputStream_.getByteString(index);
        }
        /**
         * <code>repeated string output_stream = 4;</code>
         */
        public Builder setOutputStream(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputStreamIsMutable();
          outputStream_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string output_stream = 4;</code>
         */
        public Builder addOutputStream(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputStreamIsMutable();
          outputStream_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string output_stream = 4;</code>
         */
        public Builder addAllOutputStream(
            java.lang.Iterable<java.lang.String> values) {
          ensureOutputStreamIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, outputStream_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string output_stream = 4;</code>
         */
        public Builder clearOutputStream() {
          outputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string output_stream = 4;</code>
         */
        public Builder addOutputStreamBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureOutputStreamIsMutable();
          outputStream_.add(value);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:MediaGraphConfig.Node)
      }

      // @@protoc_insertion_point(class_scope:MediaGraphConfig.Node)
      private static final MediaGraphConfigProto.MediaGraphConfig.Node DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new MediaGraphConfigProto.MediaGraphConfig.Node();
      }

      public static MediaGraphConfigProto.MediaGraphConfig.Node getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Node>
          PARSER = new com.google.protobuf.AbstractParser<Node>() {
        @java.lang.Override
        public Node parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Node(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Node> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Node> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public MediaGraphConfigProto.MediaGraphConfig.Node getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int NODE_FIELD_NUMBER = 1;
    private java.util.List<MediaGraphConfigProto.MediaGraphConfig.Node> node_;
    /**
     * <pre>
     * The nodes.
     * </pre>
     *
     * <code>repeated .MediaGraphConfig.Node node = 1;</code>
     */
    public java.util.List<MediaGraphConfigProto.MediaGraphConfig.Node> getNodeList() {
      return node_;
    }
    /**
     * <pre>
     * The nodes.
     * </pre>
     *
     * <code>repeated .MediaGraphConfig.Node node = 1;</code>
     */
    public java.util.List<? extends MediaGraphConfigProto.MediaGraphConfig.NodeOrBuilder> 
        getNodeOrBuilderList() {
      return node_;
    }
    /**
     * <pre>
     * The nodes.
     * </pre>
     *
     * <code>repeated .MediaGraphConfig.Node node = 1;</code>
     */
    public int getNodeCount() {
      return node_.size();
    }
    /**
     * <pre>
     * The nodes.
     * </pre>
     *
     * <code>repeated .MediaGraphConfig.Node node = 1;</code>
     */
    public MediaGraphConfigProto.MediaGraphConfig.Node getNode(int index) {
      return node_.get(index);
    }
    /**
     * <pre>
     * The nodes.
     * </pre>
     *
     * <code>repeated .MediaGraphConfig.Node node = 1;</code>
     */
    public MediaGraphConfigProto.MediaGraphConfig.NodeOrBuilder getNodeOrBuilder(
        int index) {
      return node_.get(index);
    }

    public static final int INPUT_STREAM_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList inputStream_;
    /**
     * <code>repeated string input_stream = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInputStreamList() {
      return inputStream_;
    }
    /**
     * <code>repeated string input_stream = 2;</code>
     */
    public int getInputStreamCount() {
      return inputStream_.size();
    }
    /**
     * <code>repeated string input_stream = 2;</code>
     */
    public java.lang.String getInputStream(int index) {
      return inputStream_.get(index);
    }
    /**
     * <code>repeated string input_stream = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInputStreamBytes(int index) {
      return inputStream_.getByteString(index);
    }

    public static final int OUTPUT_STREAM_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList outputStream_;
    /**
     * <code>repeated string output_stream = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getOutputStreamList() {
      return outputStream_;
    }
    /**
     * <code>repeated string output_stream = 3;</code>
     */
    public int getOutputStreamCount() {
      return outputStream_.size();
    }
    /**
     * <code>repeated string output_stream = 3;</code>
     */
    public java.lang.String getOutputStream(int index) {
      return outputStream_.get(index);
    }
    /**
     * <code>repeated string output_stream = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOutputStreamBytes(int index) {
      return outputStream_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < node_.size(); i++) {
        output.writeMessage(1, node_.get(i));
      }
      for (int i = 0; i < inputStream_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, inputStream_.getRaw(i));
      }
      for (int i = 0; i < outputStream_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, outputStream_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < node_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, node_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < inputStream_.size(); i++) {
          dataSize += computeStringSizeNoTag(inputStream_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInputStreamList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < outputStream_.size(); i++) {
          dataSize += computeStringSizeNoTag(outputStream_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getOutputStreamList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MediaGraphConfigProto.MediaGraphConfig)) {
        return super.equals(obj);
      }
      MediaGraphConfigProto.MediaGraphConfig other = (MediaGraphConfigProto.MediaGraphConfig) obj;

      boolean result = true;
      result = result && getNodeList()
          .equals(other.getNodeList());
      result = result && getInputStreamList()
          .equals(other.getInputStreamList());
      result = result && getOutputStreamList()
          .equals(other.getOutputStreamList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNodeCount() > 0) {
        hash = (37 * hash) + NODE_FIELD_NUMBER;
        hash = (53 * hash) + getNodeList().hashCode();
      }
      if (getInputStreamCount() > 0) {
        hash = (37 * hash) + INPUT_STREAM_FIELD_NUMBER;
        hash = (53 * hash) + getInputStreamList().hashCode();
      }
      if (getOutputStreamCount() > 0) {
        hash = (37 * hash) + OUTPUT_STREAM_FIELD_NUMBER;
        hash = (53 * hash) + getOutputStreamList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MediaGraphConfigProto.MediaGraphConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MediaGraphConfigProto.MediaGraphConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MediaGraphConfigProto.MediaGraphConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MediaGraphConfigProto.MediaGraphConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MediaGraphConfigProto.MediaGraphConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MediaGraphConfigProto.MediaGraphConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MediaGraphConfigProto.MediaGraphConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MediaGraphConfigProto.MediaGraphConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MediaGraphConfigProto.MediaGraphConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MediaGraphConfigProto.MediaGraphConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MediaGraphConfigProto.MediaGraphConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MediaGraphConfigProto.MediaGraphConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MediaGraphConfigProto.MediaGraphConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MediaGraphConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MediaGraphConfig)
        MediaGraphConfigProto.MediaGraphConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MediaGraphConfigProto.internal_static_MediaGraphConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MediaGraphConfigProto.internal_static_MediaGraphConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MediaGraphConfigProto.MediaGraphConfig.class, MediaGraphConfigProto.MediaGraphConfig.Builder.class);
      }

      // Construct using MediaGraphConfigProto.MediaGraphConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (nodeBuilder_ == null) {
          node_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodeBuilder_.clear();
        }
        inputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        outputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MediaGraphConfigProto.internal_static_MediaGraphConfig_descriptor;
      }

      @java.lang.Override
      public MediaGraphConfigProto.MediaGraphConfig getDefaultInstanceForType() {
        return MediaGraphConfigProto.MediaGraphConfig.getDefaultInstance();
      }

      @java.lang.Override
      public MediaGraphConfigProto.MediaGraphConfig build() {
        MediaGraphConfigProto.MediaGraphConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MediaGraphConfigProto.MediaGraphConfig buildPartial() {
        MediaGraphConfigProto.MediaGraphConfig result = new MediaGraphConfigProto.MediaGraphConfig(this);
        int from_bitField0_ = bitField0_;
        if (nodeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            node_ = java.util.Collections.unmodifiableList(node_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.node_ = node_;
        } else {
          result.node_ = nodeBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          inputStream_ = inputStream_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.inputStream_ = inputStream_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          outputStream_ = outputStream_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.outputStream_ = outputStream_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MediaGraphConfigProto.MediaGraphConfig) {
          return mergeFrom((MediaGraphConfigProto.MediaGraphConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MediaGraphConfigProto.MediaGraphConfig other) {
        if (other == MediaGraphConfigProto.MediaGraphConfig.getDefaultInstance()) return this;
        if (nodeBuilder_ == null) {
          if (!other.node_.isEmpty()) {
            if (node_.isEmpty()) {
              node_ = other.node_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodeIsMutable();
              node_.addAll(other.node_);
            }
            onChanged();
          }
        } else {
          if (!other.node_.isEmpty()) {
            if (nodeBuilder_.isEmpty()) {
              nodeBuilder_.dispose();
              nodeBuilder_ = null;
              node_ = other.node_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodeFieldBuilder() : null;
            } else {
              nodeBuilder_.addAllMessages(other.node_);
            }
          }
        }
        if (!other.inputStream_.isEmpty()) {
          if (inputStream_.isEmpty()) {
            inputStream_ = other.inputStream_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureInputStreamIsMutable();
            inputStream_.addAll(other.inputStream_);
          }
          onChanged();
        }
        if (!other.outputStream_.isEmpty()) {
          if (outputStream_.isEmpty()) {
            outputStream_ = other.outputStream_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureOutputStreamIsMutable();
            outputStream_.addAll(other.outputStream_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MediaGraphConfigProto.MediaGraphConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MediaGraphConfigProto.MediaGraphConfig) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<MediaGraphConfigProto.MediaGraphConfig.Node> node_ =
        java.util.Collections.emptyList();
      private void ensureNodeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          node_ = new java.util.ArrayList<MediaGraphConfigProto.MediaGraphConfig.Node>(node_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MediaGraphConfigProto.MediaGraphConfig.Node, MediaGraphConfigProto.MediaGraphConfig.Node.Builder, MediaGraphConfigProto.MediaGraphConfig.NodeOrBuilder> nodeBuilder_;

      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public java.util.List<MediaGraphConfigProto.MediaGraphConfig.Node> getNodeList() {
        if (nodeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(node_);
        } else {
          return nodeBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public int getNodeCount() {
        if (nodeBuilder_ == null) {
          return node_.size();
        } else {
          return nodeBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public MediaGraphConfigProto.MediaGraphConfig.Node getNode(int index) {
        if (nodeBuilder_ == null) {
          return node_.get(index);
        } else {
          return nodeBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public Builder setNode(
          int index, MediaGraphConfigProto.MediaGraphConfig.Node value) {
        if (nodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeIsMutable();
          node_.set(index, value);
          onChanged();
        } else {
          nodeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public Builder setNode(
          int index, MediaGraphConfigProto.MediaGraphConfig.Node.Builder builderForValue) {
        if (nodeBuilder_ == null) {
          ensureNodeIsMutable();
          node_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public Builder addNode(MediaGraphConfigProto.MediaGraphConfig.Node value) {
        if (nodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeIsMutable();
          node_.add(value);
          onChanged();
        } else {
          nodeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public Builder addNode(
          int index, MediaGraphConfigProto.MediaGraphConfig.Node value) {
        if (nodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeIsMutable();
          node_.add(index, value);
          onChanged();
        } else {
          nodeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public Builder addNode(
          MediaGraphConfigProto.MediaGraphConfig.Node.Builder builderForValue) {
        if (nodeBuilder_ == null) {
          ensureNodeIsMutable();
          node_.add(builderForValue.build());
          onChanged();
        } else {
          nodeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public Builder addNode(
          int index, MediaGraphConfigProto.MediaGraphConfig.Node.Builder builderForValue) {
        if (nodeBuilder_ == null) {
          ensureNodeIsMutable();
          node_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public Builder addAllNode(
          java.lang.Iterable<? extends MediaGraphConfigProto.MediaGraphConfig.Node> values) {
        if (nodeBuilder_ == null) {
          ensureNodeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, node_);
          onChanged();
        } else {
          nodeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public Builder clearNode() {
        if (nodeBuilder_ == null) {
          node_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodeBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public Builder removeNode(int index) {
        if (nodeBuilder_ == null) {
          ensureNodeIsMutable();
          node_.remove(index);
          onChanged();
        } else {
          nodeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public MediaGraphConfigProto.MediaGraphConfig.Node.Builder getNodeBuilder(
          int index) {
        return getNodeFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public MediaGraphConfigProto.MediaGraphConfig.NodeOrBuilder getNodeOrBuilder(
          int index) {
        if (nodeBuilder_ == null) {
          return node_.get(index);  } else {
          return nodeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public java.util.List<? extends MediaGraphConfigProto.MediaGraphConfig.NodeOrBuilder> 
           getNodeOrBuilderList() {
        if (nodeBuilder_ != null) {
          return nodeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(node_);
        }
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public MediaGraphConfigProto.MediaGraphConfig.Node.Builder addNodeBuilder() {
        return getNodeFieldBuilder().addBuilder(
            MediaGraphConfigProto.MediaGraphConfig.Node.getDefaultInstance());
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public MediaGraphConfigProto.MediaGraphConfig.Node.Builder addNodeBuilder(
          int index) {
        return getNodeFieldBuilder().addBuilder(
            index, MediaGraphConfigProto.MediaGraphConfig.Node.getDefaultInstance());
      }
      /**
       * <pre>
       * The nodes.
       * </pre>
       *
       * <code>repeated .MediaGraphConfig.Node node = 1;</code>
       */
      public java.util.List<MediaGraphConfigProto.MediaGraphConfig.Node.Builder> 
           getNodeBuilderList() {
        return getNodeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MediaGraphConfigProto.MediaGraphConfig.Node, MediaGraphConfigProto.MediaGraphConfig.Node.Builder, MediaGraphConfigProto.MediaGraphConfig.NodeOrBuilder> 
          getNodeFieldBuilder() {
        if (nodeBuilder_ == null) {
          nodeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MediaGraphConfigProto.MediaGraphConfig.Node, MediaGraphConfigProto.MediaGraphConfig.Node.Builder, MediaGraphConfigProto.MediaGraphConfig.NodeOrBuilder>(
                  node_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          node_ = null;
        }
        return nodeBuilder_;
      }

      private com.google.protobuf.LazyStringList inputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInputStreamIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          inputStream_ = new com.google.protobuf.LazyStringArrayList(inputStream_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string input_stream = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInputStreamList() {
        return inputStream_.getUnmodifiableView();
      }
      /**
       * <code>repeated string input_stream = 2;</code>
       */
      public int getInputStreamCount() {
        return inputStream_.size();
      }
      /**
       * <code>repeated string input_stream = 2;</code>
       */
      public java.lang.String getInputStream(int index) {
        return inputStream_.get(index);
      }
      /**
       * <code>repeated string input_stream = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInputStreamBytes(int index) {
        return inputStream_.getByteString(index);
      }
      /**
       * <code>repeated string input_stream = 2;</code>
       */
      public Builder setInputStream(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInputStreamIsMutable();
        inputStream_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string input_stream = 2;</code>
       */
      public Builder addInputStream(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInputStreamIsMutable();
        inputStream_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string input_stream = 2;</code>
       */
      public Builder addAllInputStream(
          java.lang.Iterable<java.lang.String> values) {
        ensureInputStreamIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, inputStream_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string input_stream = 2;</code>
       */
      public Builder clearInputStream() {
        inputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string input_stream = 2;</code>
       */
      public Builder addInputStreamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureInputStreamIsMutable();
        inputStream_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList outputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureOutputStreamIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          outputStream_ = new com.google.protobuf.LazyStringArrayList(outputStream_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string output_stream = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getOutputStreamList() {
        return outputStream_.getUnmodifiableView();
      }
      /**
       * <code>repeated string output_stream = 3;</code>
       */
      public int getOutputStreamCount() {
        return outputStream_.size();
      }
      /**
       * <code>repeated string output_stream = 3;</code>
       */
      public java.lang.String getOutputStream(int index) {
        return outputStream_.get(index);
      }
      /**
       * <code>repeated string output_stream = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOutputStreamBytes(int index) {
        return outputStream_.getByteString(index);
      }
      /**
       * <code>repeated string output_stream = 3;</code>
       */
      public Builder setOutputStream(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputStreamIsMutable();
        outputStream_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string output_stream = 3;</code>
       */
      public Builder addOutputStream(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureOutputStreamIsMutable();
        outputStream_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string output_stream = 3;</code>
       */
      public Builder addAllOutputStream(
          java.lang.Iterable<java.lang.String> values) {
        ensureOutputStreamIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, outputStream_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string output_stream = 3;</code>
       */
      public Builder clearOutputStream() {
        outputStream_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string output_stream = 3;</code>
       */
      public Builder addOutputStreamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureOutputStreamIsMutable();
        outputStream_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MediaGraphConfig)
    }

    // @@protoc_insertion_point(class_scope:MediaGraphConfig)
    private static final MediaGraphConfigProto.MediaGraphConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MediaGraphConfigProto.MediaGraphConfig();
    }

    public static MediaGraphConfigProto.MediaGraphConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MediaGraphConfig>
        PARSER = new com.google.protobuf.AbstractParser<MediaGraphConfig>() {
      @java.lang.Override
      public MediaGraphConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MediaGraphConfig(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MediaGraphConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MediaGraphConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MediaGraphConfigProto.MediaGraphConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MediaGraphConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MediaGraphConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MediaGraphConfig_Node_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MediaGraphConfig_Node_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026MediaGraphConfig.proto\"\274\001\n\020MediaGraphC" +
      "onfig\022$\n\004node\030\001 \003(\0132\026.MediaGraphConfig.N" +
      "ode\022\024\n\014input_stream\030\002 \003(\t\022\025\n\routput_stre" +
      "am\030\003 \003(\t\032U\n\004Node\022\014\n\004name\030\001 \001(\t\022\022\n\ncalcul" +
      "ator\030\002 \001(\t\022\024\n\014input_stream\030\003 \003(\t\022\025\n\routp" +
      "ut_stream\030\004 \003(\tB\027B\025MediaGraphConfigProto" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MediaGraphConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MediaGraphConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MediaGraphConfig_descriptor,
        new java.lang.String[] { "Node", "InputStream", "OutputStream", });
    internal_static_MediaGraphConfig_Node_descriptor =
      internal_static_MediaGraphConfig_descriptor.getNestedTypes().get(0);
    internal_static_MediaGraphConfig_Node_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MediaGraphConfig_Node_descriptor,
        new java.lang.String[] { "Name", "Calculator", "InputStream", "OutputStream", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
