// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_test_2eproto__INCLUDED
#define PROTOBUF_test_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace media {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_test_2eproto();
void protobuf_InitDefaults_test_2eproto();
void protobuf_AssignDesc_test_2eproto();
void protobuf_ShutdownFile_test_2eproto();

class CalculatorOptions;

// ===================================================================

class CalculatorOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:media.CalculatorOptions) */ {
 public:
  CalculatorOptions();
  virtual ~CalculatorOptions();

  CalculatorOptions(const CalculatorOptions& from);

  inline CalculatorOptions& operator=(const CalculatorOptions& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CalculatorOptions& default_instance();

  static const CalculatorOptions* internal_default_instance();

  void Swap(CalculatorOptions* other);

  // implements Message ----------------------------------------------

  inline CalculatorOptions* New() const { return New(NULL); }

  CalculatorOptions* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CalculatorOptions& from);
  void MergeFrom(const CalculatorOptions& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CalculatorOptions* other);
  void UnsafeMergeFrom(const CalculatorOptions& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool merge_fields = 1 [deprecated = true];
  GOOGLE_PROTOBUF_DEPRECATED_ATTR bool has_merge_fields() const;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR void clear_merge_fields();
  GOOGLE_PROTOBUF_DEPRECATED_ATTR static const int kMergeFieldsFieldNumber = 1;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR bool merge_fields() const;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR void set_merge_fields(bool value);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(CalculatorOptions)
  // @@protoc_insertion_point(class_scope:media.CalculatorOptions)
 private:
  inline void set_has_merge_fields();
  inline void clear_has_merge_fields();

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  bool merge_fields_;
  friend void  protobuf_InitDefaults_test_2eproto_impl();
  friend void  protobuf_AddDesc_test_2eproto_impl();
  friend void protobuf_AssignDesc_test_2eproto();
  friend void protobuf_ShutdownFile_test_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<CalculatorOptions> CalculatorOptions_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CalculatorOptions

// optional bool merge_fields = 1 [deprecated = true];
inline bool CalculatorOptions::has_merge_fields() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CalculatorOptions::set_has_merge_fields() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CalculatorOptions::clear_has_merge_fields() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CalculatorOptions::clear_merge_fields() {
  merge_fields_ = false;
  clear_has_merge_fields();
}
inline bool CalculatorOptions::merge_fields() const {
  // @@protoc_insertion_point(field_get:media.CalculatorOptions.merge_fields)
  return merge_fields_;
}
inline void CalculatorOptions::set_merge_fields(bool value) {
  set_has_merge_fields();
  merge_fields_ = value;
  // @@protoc_insertion_point(field_set:media.CalculatorOptions.merge_fields)
}

inline const CalculatorOptions* CalculatorOptions::internal_default_instance() {
  return &CalculatorOptions_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace media

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_test_2eproto__INCLUDED
